### PR TITLE
First gitlab port for a chart

### PR DESCRIPTION
**Pull request by guineveresaenger**
Example gitlab integration that was the basis for https://github.com/samsung-cnct/solas-chart/pull/9.

### CODE REVIEW

**Comment by guineveresaenger** [comment]
Fixes https://github.com/samsung-cnct/chart-fluent-bit/issues/8.

**Comment by davidewatson** [comment]
Note that analogous versioning changes should be made for the container repositories.

**Comment by DStorck** [comment]
@guineveresaenger has @dwat 's versioning change comment been dealt with?

**Comment by guineveresaenger** [comment]
@DStorck yes. we discussed it tyesterday and I will submit a PR against the appropriate solas repository to document this. I'll ping you once that's in.

**Pull request merged**
